% demo.nu — the Neutrino tour. Load it and watch:
%
%     neutrino> load("packages/demo.nu")
%
let praw = fn t -> print(strrep(strrep(t, "{", "{{"), "}", "}}"))

% Every number printed below is computed live in this session, in the
% language it demonstrates. Seeded where random, deterministic throughout.

print("")
print("  ╭─╴   ╶─╮   N E U T R I N O — the tour")
print("    ▪ ◉ ▪     a small functional array language")
print("  ╰─╴   ╶─╯   (every result below is computed as you watch)")
print("")
print("── Act I. Executable mathematics ─────────────────────────────")
print("")
print("  Euler's Basel problem, in Euler's notation:")
print("    (sum[k = 1:n] 1/k^2) where n = 100000")
print("      => " + str((sum[k = 1:n] 1 / k ^ 2) where n = 100000) + "   (pi^2/6 = " + str(pi ^ 2 / 6) + ")")
print("")
print("  The Gaussian integral, squared — pi by the polar miracle:")
print("    (2 * integral(fn u -> exp(-u^2), 0, 10)) ^ 2")
print("      => " + str((2 * integral(fn u -> exp(-u ^ 2), 0, 10)) ^ 2))
print("")
print("── Act II. The blackboard's word order ───────────────────────")
print("")
print("  State the formula first, the constants after — 'where':")
print("    (-b + [-d, d]) / (2*a) where a = 1, b = -3, c = 2, d = sqrt(b^2 - 4*a*c)")
print("      => " + str((-b + [-d, d]) / (2 * a) where a = 1, b = -3, c = 2, d = sqrt(b ^ 2 - 4 * a * c)))
print("")
print("  Chained comparisons make masks; masks count under sums:")
print("    sum(-1.96 < z < 1.96) / n where n = 10000, z = randn(1, n)   [seeded]")
rng(2)
print("      => " + str(sum(-1.96 < z < 1.96) / n where n = 10000, z = randn(1, n)) + "   (theory: 0.95)")
print("")
print("── Act III. Pipelines ────────────────────────────────────────")
print("")
print("  The birthday problem, solved in one sentence:")
print("    1:m ~> (fn k -> prod[j = 1:k] (1 - (j-1)/365)) |> (fn p -> find(p < 0.5)[1]) where m = 60")
print("      => " + str(1:m ~> (fn k -> prod[j = 1:k] (1 - (j - 1) / 365)) |> (fn p -> find(p < 0.5)[1]) where m = 60) + " people")
print("")
print("  Fan-out: one value, many measurements — the language's thesis:")
praw("    A |> {a = det, b = inv} where A = eig(rand(2)).vectors   [seeded]")
rng(1)
praw("      => " + str(A |> {a = det, b = inv} where A = eig(rand(2)).vectors))
print("")
print("── Act IV. The calculus ──────────────────────────────────────")
print("")
load("packages/symb.nu")
print("  Symbolic differentiation, string in, string out (symb.nu):")
print("    deriv(\"sin(x)/x\")")
print("      => " + deriv("sin(x)/x"))
print("")
print("  The symbolic derivative is a function; fzero hunts its root:")
print("    fzero(dfun(\"sin(x)/x\"), 4, 5)")
praw("      => " + str(fzero(dfun("sin(x)/x"), 4, 5)) + "   (the tan x = x critical point)")
print("")
print("── Act V. Money ──────────────────────────────────────────────")
print("")
load("packages/finance.nu")
print("  The 30-year mortgage, HP-12C style (finance.nu):")
print("    pmt(360, 0.0575/12, 340000, 0)")
print("      => " + str(pmt(360, 0.0575 / 12, 340000, 0)) + " per month")
print("")
print("── Finale. Pictures ──────────────────────────────────────────")
print("")
print("  A damped wave and a seeded scatter (see the Plots tab in the")
print("  browser; gnuplot or ascii at a terminal):")
plot(0:0.1:12, exp(-(0:0.1:12) / 6) .* sin(0:0.1:12), {title = "exp(-x/6) sin(x)"})
rng(4)
load("packages/scatter.nu")
scatter_titled(rand(1, 40), 2 * rand(1, 40) + randn(1, 40) * 0.2, "seeded scatter")
print("")
print("  Tour complete. 155 builtins, 9 packages, 3 machine-verified")
print("  books — MANUAL.md, PACKAGES.md, BOOK.md. The syntax is frozen;")
print("  what you just read is what it does, permanently.")
print("")
