% demo.nu — the Neutrino tour. Load it and watch:
%
%     neutrino> load("packages/demo.nu")
%
let praw = fn t -> print(strrep(strrep(t, "{", "{{"), "}", "}}"))

% Every number printed below is computed live in this session, in the
% language it demonstrates. Seeded where random, deterministic throughout.

print("")
print("  ╭─╴   ╶─╮   N E U T R I N O — the tour")
print("    ▪ ◉ ▪     a small functional array language")
print("  ╰─╴   ╶─╯   (every result below is computed as you watch)")
print("")
print("── Act I. Executable mathematics ─────────────────────────────")
print("")
print("  Euler's Basel problem, in Euler's notation:")
print("    (sum[k = 1:n] 1/k^2) where n = 100000")
print("      => " + str((sum[k = 1:n] 1 / k ^ 2) where n = 100000) + "   (pi^2/6 = " + str(pi ^ 2 / 6) + ")")
print("")
print("  The Gaussian integral, squared — pi by the polar miracle:")
print("    (2 * integral(fn u -> exp(-u^2), 0, 10)) ^ 2")
print("      => " + str((2 * integral(fn u -> exp(-u ^ 2), 0, 10)) ^ 2))
print("")
print("── Act II. The blackboard's word order ───────────────────────")
print("")
print("  State the formula first, the constants after — 'where':")
print("    (-b + [-d, d]) / (2*a) where a = 1, b = -3, c = 2, d = sqrt(b^2 - 4*a*c)")
print("      => " + str((-b + [-d, d]) / (2 * a) where a = 1, b = -3, c = 2, d = sqrt(b ^ 2 - 4 * a * c)))
print("")
print("  Chained comparisons make masks; masks count under sums:")
print("    mean(-1.96 < z < 1.96) where z = randn(1, 10000)   [seeded]")
rng(2)
print("      => " + str(mean(-1.96 < z < 1.96) where z = randn(1, 10000)) + "   (theory: 0.95)")
print("")
print("── Act III. Functions as values ──────────────────────────────")
print("")
print("  Anonymous, applied on the spot:")
print("    (fn x -> x^2 + 1)(3)")
print("      => " + str((fn x -> x ^ 2 + 1)(3)))
print("")
print("  Recursion — Euclid's algorithm, twenty-three centuries old:")
print("    let gcd_ = fn a, b -> if b == 0 then a else gcd_(b, mod(a, b)) end")
let gcd_ = fn a, b -> if b == 0 then a else gcd_(b, mod(a, b)) end
print("    gcd_(1071, 462)  =>  " + str(gcd_(1071, 462)))
print("")
print("  Compose any function with itself n times — and find a legend:")
print("    let iterate = fn f, n -> if n <= 0 then (fn x -> x) else (fn x -> f(iterate(f, n-1)(x))) end")
let iterate = fn f, n -> if n <= 0 then (fn x -> x) else (fn x -> f(iterate(f, n - 1)(x))) end
print("    iterate(fn t -> sqrt(1 + t), 40)(1)")
print("      => " + str(iterate(fn t -> sqrt(1 + t), 40)(1)) + "   (the golden ratio: the fixed point of sqrt(1+x))")
print("")
print("── Act IV. Pipelines — the oscillation and the fan-out ───────")
print("")
print("  Values flavor-change down the pipe: element-wise through ~>,")
print("  whole through |>, and back again:")
print("    1:12 ~> (@ ^ 2) |> (fn v -> v[v > 50]) ~> sqrt |> mean")
print("      => " + str(1:12 ~> (@ ^ 2) |> (fn v -> v[v > 50]) ~> sqrt |> mean))
print("")
print("  Fan-out: one value, a whole dashboard — crown jewel #2:")
praw("    rand(1, 500) |> {mu = mean, sd = std, hi = max, lo = min}   [seeded]")
rng(7)
praw("      => " + str(rand(1, 500) |> {mu = mean, sd = std, hi = max, lo = min}))
print("")
print("  The birthday problem, solved in one sentence:")
print("    1:m ~> (fn k -> prod[j = 1:k] (1 - (j-1)/365)) |> (fn p -> find(p < 0.5)[1]) where m = 60")
print("      => " + str(1:m ~> (fn k -> prod[j = 1:k] (1 - (j - 1) / 365)) |> (fn p -> find(p < 0.5)[1]) where m = 60) + " people")
print("")
print("  Fan-out: one value, many measurements — the language's thesis:")
praw("    A |> {a = det, b = inv} where A = eig(rand(2)).vectors   [seeded]")
rng(1)
praw("      => " + str(A |> {a = det, b = inv} where A = eig(rand(2)).vectors))
print("")
print("── Act V. The calculus ──────────────────────────────────────")
print("")
load("packages/symb.nu")
print("  Symbolic differentiation, string in, string out (symb.nu):")
print("    deriv(\"sin(x)/x\")")
print("      => " + deriv("sin(x)/x"))
print("")
print("  The symbolic derivative is a function; fzero hunts its root:")
print("    fzero(dfun(\"sin(x)/x\"), 4, 5)")
praw("      => " + str(fzero(dfun("sin(x)/x"), 4, 5)) + "   (the tan x = x critical point)")
print("")
print("── Act VI. Money ──────────────────────────────────────────────")
print("")
load("packages/finance.nu")
print("  The 30-year mortgage, HP-12C style (finance.nu):")
print("    pmt(360, 0.0575/12, 340000, 0)")
print("      => " + str(pmt(360, 0.0575 / 12, 340000, 0)) + " per month")
print("")
print("── Finale. Pictures ──────────────────────────────────────────")
print("")
print("  A damped wave and a seeded scatter (see the Plots tab in the")
print("  browser; gnuplot or ascii at a terminal):")
plot(0:0.1:12, exp(-(0:0.1:12) / 6) .* sin(0:0.1:12), {title = "exp(-x/6) sin(x)"})
rng(4)
load("packages/scatter.nu")
scatter_titled(rand(1, 40), 2 * rand(1, 40) + randn(1, 40) * 0.2, "seeded scatter")
print("")
print("  Tour complete. 155 builtins, 9 packages, 3 machine-verified")
print("  books — MANUAL.md, PACKAGES.md, BOOK.md. The syntax is frozen;")
print("  what you just read is what it does, permanently.")
print("")
